apiVersion: v1
kind: Service
metadata:
    name: "azhskubernetescluster01-3a75"
    labels:
        app: "azhskubernetescluster01-3a75"
spec:
    type: LoadBalancer
    ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: http
    selector:
        app: "azhskubernetescluster01-3a75"