on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azhscr01.azurecr.io
        username: ${{ secrets.acr_azhscr01_username }}
        password: ${{ secrets.acr_azhscr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azhscr01.azurecr.io/azhskubernetescluster01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push azhscr01.azurecr.io/azhskubernetescluster01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azhskubernetescluster01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azhskubernetesnamespace01 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azhskubernetesnamespace01`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azhskubernetesnamespace01
        container-registry-url: azhscr01.azurecr.io
        container-registry-username: ${{ secrets.acr_azhscr01_username }}
        container-registry-password: ${{ secrets.acr_azhscr01_password }}
        secret-name: azhskubernetdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azhskubernetesnamespace01
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azhscr01.azurecr.io/azhskubernetescluster01:${{ github.sha }}
        imagepullsecrets: |
          azhskubernetdockerauth
